version: '3'


services:
    mysql8:
        image: mysql:8
        container_name: mysql8
        expose:
            - 3306
        ports:
            - "3306:3306"
        volumes:
            - "/home/mysql/data:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: root
